# Generated by Django 3.2.20 on 2024-03-25 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("simpleCruddalsModel", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modelc",
            name="all_exclude",
        ),
        migrations.RemoveField(
            model_name="modelc",
            name="all_input",
        ),
        migrations.RemoveField(
            model_name="modelc",
            name="create_only",
        ),
        migrations.RemoveField(
            model_name="modelc",
            name="create_update_only",
        ),
        migrations.RemoveField(
            model_name="modelc",
            name="order_by_only",
        ),
        migrations.RemoveField(
            model_name="modelc",
            name="update_only",
        ),
        migrations.RemoveField(
            model_name="modelc",
            name="where_only",
        ),
        migrations.RemoveField(
            model_name="modeld",
            name="all_exclude",
        ),
        migrations.RemoveField(
            model_name="modeld",
            name="all_input",
        ),
        migrations.RemoveField(
            model_name="modeld",
            name="create_only",
        ),
        migrations.RemoveField(
            model_name="modeld",
            name="create_update_only",
        ),
        migrations.RemoveField(
            model_name="modeld",
            name="order_by_only",
        ),
        migrations.RemoveField(
            model_name="modeld",
            name="update_only",
        ),
        migrations.RemoveField(
            model_name="modeld",
            name="where_only",
        ),
        migrations.RemoveField(
            model_name="modele",
            name="fk_f",
        ),
        migrations.RemoveField(
            model_name="modele",
            name="mtm_f",
        ),
        migrations.RemoveField(
            model_name="modele",
            name="oto_f",
        ),
        migrations.RemoveField(
            model_name="modele",
            name="text",
        ),
        migrations.AddField(
            model_name="modelc",
            name="boolean_field",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="modelc",
            name="char_field",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="modelc",
            name="date_time_field",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="modelc",
            name="file_field",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="modelc",
            name="integer_field",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="modelc",
            name="json_field",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="modelc",
            name="many_to_many_field",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="many_to_many_C_related",
                to="simpleCruddalsModel.ModelD",
            ),
        ),
        migrations.AddField(
            model_name="modelc",
            name="one_to_one_field",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="one_to_one_C_related",
                to="simpleCruddalsModel.modeld",
            ),
        ),
        migrations.AddField(
            model_name="modeld",
            name="foreign_key_field",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="foreign_key_D_related",
                to="simpleCruddalsModel.modelc",
            ),
        ),
        migrations.AddField(
            model_name="modele",
            name="foreign_key_field_deep",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="foreign_key_E_related",
                to="simpleCruddalsModel.modeld",
            ),
        ),
        migrations.DeleteModel(
            name="ModelF",
        ),
    ]
