# Generated by Django 4.2 on 2024-03-17 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], help_text='The day of the week of the schedule')),
                ('object_id', models.PositiveIntegerField(help_text='The object id of the schedule item')),
                ('is_active', models.BooleanField(default=True, help_text='The status for enabling or disabling')),
                ('content_type', models.ForeignKey(help_text='The content type of the schedule item', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(help_text='The start time of the time slot')),
                ('end_time', models.TimeField(help_text='The end time of the time slot')),
                ('is_active', models.BooleanField(default=True, help_text='The status for enabling or disabling')),
                ('schedule', models.ForeignKey(help_text='The schedule that the time slot is a part of', on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='core.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hire_date', models.DateField(help_text='The date the employee was hired')),
                ('extra_info', models.JSONField(blank=True, help_text='The extra information of the employee', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='The status for enabling or disabling')),
                ('restaurant', models.ForeignKey(help_text='The restaurant that the employee works at', on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
                ('user', models.OneToOneField(help_text='The user that has this employee profile', on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
