# Generated by Django 4.2 on 2024-03-17 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='The content type of the schedule item', limit_choices_to={'model__in': ('menu', 'employeeprofile', 'restaurant')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, help_text='The object id of the schedule item', null=True),
        ),
    ]
