# Generated by Django 4.2 on 2024-03-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
        ('core', '0002_alter_schedule_content_type_alter_schedule_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='restaurants',
            field=models.ManyToManyField(help_text='The restaurant that the employee works at', related_name='employees', to='restaurant.restaurant'),
        ),
    ]
