---
name: "💡 Feature Request "
title: "[Feature Request]: "
description: "Request a new feature for the CRUDDALS project."
labels:
  - enhancement
assignees:
  - juanjcardona13

body:
  - type: markdown
    attributes:
      value: |
        ## 💡 Feature Description:

        * Clearly describe the functionality you are suggesting for CRUDDALS.
        * What problem would this new feature solve in the context of CRUDDALS?
        * What benefits would it bring to the CRUDDALS project and its users?

  - type: textarea
    attributes:
      label: "💻 Implementation Details:"
      placeholder: |
        * Describe how the new functionality could be implemented within CRUDDALS.
        * Are there any specific components, APIs, or models from CRUDDALS that should be used?
        * Can you provide a code example or a diagram illustrating the implementation in CRUDDALS?

  - type: textarea
    attributes:
      label: "🔍 Additional Information:"
      placeholder: |
        * Share any other relevant information in the context of CRUDDALS.
        * Are there any specific use cases that should be considered within CRUDDALS?
        * Are there any other solutions or alternatives that have been explored for CRUDDALS?

  - type: checkboxes
    attributes:
      label: "🚀 Priority:"
      options:
        - label: "Low"
        - label: "Medium"
        - label: "High"
        - label: "Critical"

  - type: textarea
    attributes:
      label: "💬 Comments:"
      placeholder: |
        * Share any additional comments or questions you have.
        * Is this request related to a specific version of CRUDDALS?

---
