# Generated by Django 4.2 on 2024-03-17 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the restaurant', max_length=100)),
                ('slug', models.SlugField(blank=True, editable=False, help_text='The slug of the restaurant', max_length=100, null=True, unique=True)),
                ('logo', models.ImageField(blank=True, help_text='The logo of the restaurant', null=True, upload_to='media/restaurant/logos/')),
                ('email', models.EmailField(help_text='The email of the restaurant', max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, help_text='The phone number of the restaurant', max_length=20, null=True)),
                ('website', models.URLField(blank=True, help_text='The website of the restaurant', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the restaurant was created')),
                ('document', models.FileField(blank=True, help_text='The document of the restaurant', null=True, upload_to='media/restaurant/documents/')),
                ('is_active', models.BooleanField(default=True, help_text='The status for enabling or disabling')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text='The identifier of the table', max_length=100)),
                ('capacity', models.IntegerField(help_text='The capacity of the table')),
                ('status', models.CharField(blank=True, choices=[('OCCUPIED', 'OCCUPIED'), ('AVAILABLE', 'AVAILABLE'), ('RESERVED', 'RESERVED'), ('UNAVAILABLE', 'UNAVAILABLE')], default='AVAILABLE', help_text='The status of the table', max_length=15, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='The status for enabling or disabling')),
                ('restaurant', models.ForeignKey(help_text='The restaurant that the table is a part of', on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='restaurant.restaurant')),
            ],
        ),
    ]
