# Generated by Django 4.2 on 2024-03-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_employeeprofile_restaurants'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='employees',
            field=models.ManyToManyField(help_text='The employees that work at the restaurant', related_name='restaurants', to='core.employeeprofile'),
        ),
    ]
