OrderByModelAInput = [
    {
        "name": "id",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "booleanFieldRequired",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "booleanFieldNotEditable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "booleanFieldNullable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "booleanFieldWithDefault",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "booleanFieldWithDescription",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "charFieldRequired",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderStringEnum", "ofType": None},
    },
    {
        "name": "charFieldNotEditable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderStringEnum", "ofType": None},
    },
    {
        "name": "charFieldNullable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderStringEnum", "ofType": None},
    },
    {
        "name": "charFieldWithDefault",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderStringEnum", "ofType": None},
    },
    {
        "name": "charFieldWithDescription",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderStringEnum", "ofType": None},
    },
    {
        "name": "choiceFieldRequired",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderStringEnum", "ofType": None},
    },
    {
        "name": "choiceFieldNotEditable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderStringEnum", "ofType": None},
    },
    {
        "name": "choiceFieldNullable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderStringEnum", "ofType": None},
    },
    {
        "name": "choiceFieldWithDefault",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderStringEnum", "ofType": None},
    },
    {
        "name": "choiceFieldWithDescription",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderStringEnum", "ofType": None},
    },
    {
        "name": "dateFieldRequired",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "dateFieldNotEditable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "dateFieldNullable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "dateFieldWithDefault",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "dateFieldWithDescription",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "dateTimeFieldRequired",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "dateTimeFieldNotEditable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "dateTimeFieldNullable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "dateTimeFieldWithDefault",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "dateTimeFieldWithDescription",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "timeFieldRequired",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "timeFieldNotEditable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "timeFieldNullable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "timeFieldWithDefault",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "timeFieldWithDescription",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "decimalFieldRequired",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "decimalFieldNotEditable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "decimalFieldNullable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "decimalFieldWithDefault",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "decimalFieldWithDescription",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "durationFieldRequired",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "durationFieldNotEditable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "durationFieldNullable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "durationFieldWithDefault",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "durationFieldWithDescription",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "emailFieldRequired",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderStringEnum", "ofType": None},
    },
    {
        "name": "emailFieldNotEditable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderStringEnum", "ofType": None},
    },
    {
        "name": "emailFieldNullable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderStringEnum", "ofType": None},
    },
    {
        "name": "emailFieldWithDefault",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderStringEnum", "ofType": None},
    },
    {
        "name": "emailFieldWithDescription",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderStringEnum", "ofType": None},
    },
    {
        "name": "floatFieldRequired",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "floatFieldNotEditable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "floatFieldNullable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "floatFieldWithDefault",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "floatFieldWithDescription",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "integerFieldRequired",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "integerFieldNotEditable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "integerFieldNullable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "integerFieldWithDefault",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "integerFieldWithDescription",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "positiveIntegerFieldRequired",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "positiveIntegerFieldNotEditable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "positiveIntegerFieldNullable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "positiveIntegerFieldWithDefault",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "positiveIntegerFieldWithDescription",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "smallIntegerFieldRequired",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "smallIntegerFieldNotEditable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "smallIntegerFieldNullable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "smallIntegerFieldWithDefault",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "smallIntegerFieldWithDescription",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "positiveSmallIntegerFieldRequired",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "positiveSmallIntegerFieldNotEditable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "positiveSmallIntegerFieldNullable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "positiveSmallIntegerFieldWithDefault",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "positiveSmallIntegerFieldWithDescription",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "bigIntegerFieldRequired",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "bigIntegerFieldNotEditable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "bigIntegerFieldNullable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "bigIntegerFieldWithDefault",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "bigIntegerFieldWithDescription",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "positiveBigIntegerFieldRequired",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "positiveBigIntegerFieldNotEditable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "positiveBigIntegerFieldNullable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "positiveBigIntegerFieldWithDefault",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "positiveBigIntegerFieldWithDescription",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "slugFieldRequired",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderStringEnum", "ofType": None},
    },
    {
        "name": "slugFieldNotEditable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderStringEnum", "ofType": None},
    },
    {
        "name": "slugFieldNullable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderStringEnum", "ofType": None},
    },
    {
        "name": "slugFieldWithDefault",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderStringEnum", "ofType": None},
    },
    {
        "name": "slugFieldWithDescription",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderStringEnum", "ofType": None},
    },
    {
        "name": "textFieldRequired",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderStringEnum", "ofType": None},
    },
    {
        "name": "textFieldNotEditable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderStringEnum", "ofType": None},
    },
    {
        "name": "textFieldNullable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderStringEnum", "ofType": None},
    },
    {
        "name": "textFieldWithDefault",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderStringEnum", "ofType": None},
    },
    {
        "name": "textFieldWithDescription",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderStringEnum", "ofType": None},
    },
    {
        "name": "urlFieldRequired",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderStringEnum", "ofType": None},
    },
    {
        "name": "urlFieldNotEditable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderStringEnum", "ofType": None},
    },
    {
        "name": "urlFieldNullable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderStringEnum", "ofType": None},
    },
    {
        "name": "urlFieldWithDefault",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderStringEnum", "ofType": None},
    },
    {
        "name": "urlFieldWithDescription",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderStringEnum", "ofType": None},
    },
    {
        "name": "genericIpAddressFieldRequired",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderStringEnum", "ofType": None},
    },
    {
        "name": "genericIpAddressFieldNotEditable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderStringEnum", "ofType": None},
    },
    {
        "name": "genericIpAddressFieldNullable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderStringEnum", "ofType": None},
    },
    {
        "name": "genericIpAddressFieldWithDefault",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderStringEnum", "ofType": None},
    },
    {
        "name": "ipAddressFieldRequired",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderStringEnum", "ofType": None},
    },
    {
        "name": "ipAddressFieldNotEditable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderStringEnum", "ofType": None},
    },
    {
        "name": "ipAddressFieldNullable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderStringEnum", "ofType": None},
    },
    {
        "name": "ipAddressFieldWithDefault",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderStringEnum", "ofType": None},
    },
    {
        "name": "uuidFieldRequired",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "uuidFieldNotEditable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "uuidFieldNullable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "uuidFieldWithDefault",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "uuidFieldWithDescription",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "foreignKeyFieldRequired",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "INPUT_OBJECT", "name": "OrderByModelAInput", "ofType": None},
    },
    {
        "name": "foreignKeyFieldNullable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "INPUT_OBJECT", "name": "OrderByModelAInput", "ofType": None},
    },
    {
        "name": "foreignKeyFieldWithDescription",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "INPUT_OBJECT", "name": "OrderByModelAInput", "ofType": None},
    },
    {
        "name": "foreignKeyFieldWithoutRelatedName",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "INPUT_OBJECT", "name": "OrderByModelAInput", "ofType": None},
    },
    {
        "name": "objectId",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "ENUM", "name": "OrderEnum", "ofType": None},
    },
    {
        "name": "oneToOneRelated",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "INPUT_OBJECT", "name": "OrderByModelAInput", "ofType": None},
    },
    {
        "name": "oneToOneNullableRelated",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "INPUT_OBJECT", "name": "OrderByModelAInput", "ofType": None},
    },
    {
        "name": "oneToOneWithDescriptionRelated",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "INPUT_OBJECT", "name": "OrderByModelAInput", "ofType": None},
    },
    {
        "name": "oneToOneBRelated",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "INPUT_OBJECT", "name": "OrderByModelBInput", "ofType": None},
    },
]
