UpdateModelAInput = [
    {
        "name": "id",
        "description": None,
        "defaultValue": None,
        "type": {
            "kind": "NON_NULL",
            "name": None,
            "ofType": {"kind": "SCALAR", "name": "ID", "ofType": None},
        },
    },
    {
        "name": "binaryFieldRequired",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "Binary", "ofType": None},
    },
    {
        "name": "binaryFieldNullable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "Binary", "ofType": None},
    },
    {
        "name": "binaryFieldWithDefault",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "Binary", "ofType": None},
    },
    {
        "name": "binaryFieldWithDescription",
        "description": "binary_field_with_description",
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "Binary", "ofType": None},
    },
    {
        "name": "booleanFieldRequired",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "Boolean", "ofType": None},
    },
    {
        "name": "booleanFieldNullable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "Boolean", "ofType": None},
    },
    {
        "name": "booleanFieldWithDefault",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "Boolean", "ofType": None},
    },
    {
        "name": "booleanFieldWithDescription",
        "description": "boolean_field_with_description",
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "Boolean", "ofType": None},
    },
    {
        "name": "charFieldRequired",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "String", "ofType": None},
    },
    {
        "name": "charFieldNullable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "String", "ofType": None},
    },
    {
        "name": "charFieldWithDefault",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "String", "ofType": None},
    },
    {
        "name": "charFieldWithDescription",
        "description": "char_field_with_description",
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "String", "ofType": None},
    },
    {
        "name": "choiceFieldRequired",
        "description": None,
        "defaultValue": None,
        "type": {
            "kind": "ENUM",
            "name": "TestsModelAChoiceFieldRequiredChoices",
            "ofType": None,
        },
    },
    {
        "name": "choiceFieldNullable",
        "description": None,
        "defaultValue": None,
        "type": {
            "kind": "ENUM",
            "name": "TestsModelAChoiceFieldNullableChoices",
            "ofType": None,
        },
    },
    {
        "name": "choiceFieldWithDefault",
        "description": None,
        "defaultValue": None,
        "type": {
            "kind": "ENUM",
            "name": "TestsModelAChoiceFieldWithDefaultChoices",
            "ofType": None,
        },
    },
    {
        "name": "choiceFieldWithDescription",
        "description": "choice_field_with_description",
        "defaultValue": None,
        "type": {
            "kind": "ENUM",
            "name": "TestsModelAChoiceFieldWithDescriptionChoices",
            "ofType": None,
        },
    },
    {
        "name": "dateFieldRequired",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "Date", "ofType": None},
    },
    {
        "name": "dateFieldNullable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "Date", "ofType": None},
    },
    {
        "name": "dateFieldWithDescription",
        "description": "date_field_with_description",
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "Date", "ofType": None},
    },
    {
        "name": "dateTimeFieldRequired",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "DateTime", "ofType": None},
    },
    {
        "name": "dateTimeFieldNullable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "DateTime", "ofType": None},
    },
    {
        "name": "dateTimeFieldWithDescription",
        "description": "date_time_field_with_description",
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "DateTime", "ofType": None},
    },
    {
        "name": "timeFieldRequired",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "Time", "ofType": None},
    },
    {
        "name": "timeFieldNullable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "Time", "ofType": None},
    },
    {
        "name": "timeFieldWithDescription",
        "description": "time_field_with_description",
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "Time", "ofType": None},
    },
    {
        "name": "decimalFieldRequired",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "Decimal", "ofType": None},
    },
    {
        "name": "decimalFieldNullable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "Decimal", "ofType": None},
    },
    {
        "name": "decimalFieldWithDefault",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "Decimal", "ofType": None},
    },
    {
        "name": "decimalFieldWithDescription",
        "description": "decimal_field_with_description",
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "Decimal", "ofType": None},
    },
    {
        "name": "durationFieldRequired",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "Duration", "ofType": None},
    },
    {
        "name": "durationFieldNullable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "Duration", "ofType": None},
    },
    {
        "name": "durationFieldWithDefault",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "Duration", "ofType": None},
    },
    {
        "name": "durationFieldWithDescription",
        "description": "duration_field_with_description",
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "Duration", "ofType": None},
    },
    {
        "name": "emailFieldRequired",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "Email", "ofType": None},
    },
    {
        "name": "emailFieldNullable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "Email", "ofType": None},
    },
    {
        "name": "emailFieldWithDefault",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "Email", "ofType": None},
    },
    {
        "name": "emailFieldWithDescription",
        "description": "email_field_with_description",
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "Email", "ofType": None},
    },
    {
        "name": "floatFieldRequired",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "Float", "ofType": None},
    },
    {
        "name": "floatFieldNullable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "Float", "ofType": None},
    },
    {
        "name": "floatFieldWithDefault",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "Float", "ofType": None},
    },
    {
        "name": "floatFieldWithDescription",
        "description": "float_field_with_description",
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "Float", "ofType": None},
    },
    {
        "name": "integerFieldRequired",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "Int", "ofType": None},
    },
    {
        "name": "integerFieldNullable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "Int", "ofType": None},
    },
    {
        "name": "integerFieldWithDefault",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "Int", "ofType": None},
    },
    {
        "name": "integerFieldWithDescription",
        "description": "integer_field_with_description",
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "Int", "ofType": None},
    },
    {
        "name": "positiveIntegerFieldRequired",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "PositiveInt", "ofType": None},
    },
    {
        "name": "positiveIntegerFieldNullable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "PositiveInt", "ofType": None},
    },
    {
        "name": "positiveIntegerFieldWithDefault",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "PositiveInt", "ofType": None},
    },
    {
        "name": "positiveIntegerFieldWithDescription",
        "description": "positive_integer_field_with_description",
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "PositiveInt", "ofType": None},
    },
    {
        "name": "smallIntegerFieldRequired",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "Int", "ofType": None},
    },
    {
        "name": "smallIntegerFieldNullable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "Int", "ofType": None},
    },
    {
        "name": "smallIntegerFieldWithDefault",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "Int", "ofType": None},
    },
    {
        "name": "smallIntegerFieldWithDescription",
        "description": "small_integer_field_with_description",
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "Int", "ofType": None},
    },
    {
        "name": "positiveSmallIntegerFieldRequired",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "Int", "ofType": None},
    },
    {
        "name": "positiveSmallIntegerFieldNullable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "Int", "ofType": None},
    },
    {
        "name": "positiveSmallIntegerFieldWithDefault",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "Int", "ofType": None},
    },
    {
        "name": "positiveSmallIntegerFieldWithDescription",
        "description": "positive_small_integer_field_with_description",
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "Int", "ofType": None},
    },
    {
        "name": "bigIntegerFieldRequired",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "BigInt", "ofType": None},
    },
    {
        "name": "bigIntegerFieldNullable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "BigInt", "ofType": None},
    },
    {
        "name": "bigIntegerFieldWithDefault",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "BigInt", "ofType": None},
    },
    {
        "name": "bigIntegerFieldWithDescription",
        "description": "big_integer_field_with_description",
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "BigInt", "ofType": None},
    },
    {
        "name": "positiveBigIntegerFieldRequired",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "BigInt", "ofType": None},
    },
    {
        "name": "positiveBigIntegerFieldNullable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "BigInt", "ofType": None},
    },
    {
        "name": "positiveBigIntegerFieldWithDefault",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "BigInt", "ofType": None},
    },
    {
        "name": "positiveBigIntegerFieldWithDescription",
        "description": "positive_big_integer_field_with_description",
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "BigInt", "ofType": None},
    },
    {
        "name": "slugFieldRequired",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "Slug", "ofType": None},
    },
    {
        "name": "slugFieldNullable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "Slug", "ofType": None},
    },
    {
        "name": "slugFieldWithDefault",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "Slug", "ofType": None},
    },
    {
        "name": "slugFieldWithDescription",
        "description": "slug_field_with_description",
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "Slug", "ofType": None},
    },
    {
        "name": "textFieldRequired",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "String", "ofType": None},
    },
    {
        "name": "textFieldNullable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "String", "ofType": None},
    },
    {
        "name": "textFieldWithDefault",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "String", "ofType": None},
    },
    {
        "name": "textFieldWithDescription",
        "description": "text_field_with_description",
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "String", "ofType": None},
    },
    {
        "name": "urlFieldRequired",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "URL", "ofType": None},
    },
    {
        "name": "urlFieldNullable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "URL", "ofType": None},
    },
    {
        "name": "urlFieldWithDefault",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "URL", "ofType": None},
    },
    {
        "name": "urlFieldWithDescription",
        "description": "url_field_with_description",
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "URL", "ofType": None},
    },
    {
        "name": "genericIpAddressFieldRequired",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "IPv4", "ofType": None},
    },
    {
        "name": "genericIpAddressFieldNullable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "IPv4", "ofType": None},
    },
    {
        "name": "genericIpAddressFieldWithDefault",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "IPv4", "ofType": None},
    },
    {
        "name": "ipAddressFieldRequired",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "IP", "ofType": None},
    },
    {
        "name": "ipAddressFieldNullable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "IP", "ofType": None},
    },
    {
        "name": "ipAddressFieldWithDefault",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "IP", "ofType": None},
    },
    {
        "name": "uuidFieldRequired",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "UUID", "ofType": None},
    },
    {
        "name": "uuidFieldNullable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "UUID", "ofType": None},
    },
    {
        "name": "uuidFieldWithDefault",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "UUID", "ofType": None},
    },
    {
        "name": "uuidFieldWithDescription",
        "description": "uuid_field_with_description",
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "UUID", "ofType": None},
    },
    {
        "name": "foreignKeyFieldRequired",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "ID", "ofType": None},
    },
    {
        "name": "foreignKeyFieldNullable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "ID", "ofType": None},
    },
    {
        "name": "foreignKeyFieldWithDescription",
        "description": "foreign_key_field_with_description",
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "ID", "ofType": None},
    },
    {
        "name": "foreignKeyFieldWithoutRelatedName",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "ID", "ofType": None},
    },
    {
        "name": "oneToOneFieldRequired",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "ID", "ofType": None},
    },
    {
        "name": "oneToOneFieldNullable",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "ID", "ofType": None},
    },
    {
        "name": "oneToOneFieldWithDescription",
        "description": "one_to_one_field_with_description",
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "ID", "ofType": None},
    },
    {
        "name": "oneToOneFieldWithoutRelatedName",
        "description": None,
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "ID", "ofType": None},
    },
    {
        "name": "contentType",
        "description": "The content type",
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "ID", "ofType": None},
    },
    {
        "name": "objectId",
        "description": "The object id",
        "defaultValue": None,
        "type": {"kind": "SCALAR", "name": "PositiveInt", "ofType": None},
    },
    {
        "name": "manyToManyFieldRequired",
        "description": None,
        "defaultValue": None,
        "type": {
            "kind": "LIST",
            "name": None,
            "ofType": {"kind": "SCALAR", "name": "ID", "ofType": None},
        },
    },
    {
        "name": "manyToManyFieldNullable",
        "description": None,
        "defaultValue": None,
        "type": {
            "kind": "LIST",
            "name": None,
            "ofType": {"kind": "SCALAR", "name": "ID", "ofType": None},
        },
    },
    {
        "name": "manyToManyFieldWithDescription",
        "description": "many_to_many_field_with_description",
        "defaultValue": None,
        "type": {
            "kind": "LIST",
            "name": None,
            "ofType": {"kind": "SCALAR", "name": "ID", "ofType": None},
        },
    },
    {
        "name": "manyToManyFieldWithoutRelatedName",
        "description": None,
        "defaultValue": None,
        "type": {
            "kind": "LIST",
            "name": None,
            "ofType": {"kind": "SCALAR", "name": "ID", "ofType": None},
        },
    },
]
