#region ============= SIMPLECRUDDALSMODEL

#region ============= MODELA

query readModelA($where: ModelAFilterInput! ) {
    readModelA(where: $where ) {
        id
    }
}

query listModelAs() {
    listModelAs() {
        total
        page
        pages
        hasNext
        hasPrev
        indexStartObj
        indexEndObj
        objects {
            id
        }
    }
}

query searchModelAs($where: ModelAFilterInput $orderBy: ModelAOrderByInput $paginated: PaginationConfigInput ) {
    searchModelAs(where: $where orderBy: $orderBy paginated: $paginated ) {
        total
        page
        pages
        hasNext
        hasPrev
        indexStartObj
        indexEndObj
        objects {
            id
        }
    }
}

mutation createModelAs($input: [CreateModelAInput!] ) {
    createModelAs(input: $input ) {
        objects {
            id
        }
        errors {
            objectPosition
            errors {
                field
                messages
            }
        }
    }
}

mutation updateModelAs($input: [UpdateModelAInput!] ) {
    updateModelAs(input: $input ) {
        objects {
            id
        }
        errors {
            objectPosition
            errors {
                field
                messages
            }
        }
    }
}

mutation deleteModelAs($where: ModelAFilterInput! ) {
    deleteModelAs(where: $where ) {
        success
        objects {
            id
        }
        errors {
            objectPosition
            errors {
                field
                messages
            }
        }
    }
}

mutation deactivateModelAs($where: ModelAFilterInput! ) {
    deactivateModelAs(where: $where ) {
        objects {
            id
        }
        errors {
            objectPosition
            errors {
                field
                messages
            }
        }
    }
}

mutation activateModelAs($where: ModelAFilterInput! ) {
    activateModelAs(where: $where ) {
        objects {
            id
        }
        errors {
            objectPosition
            errors {
                field
                messages
            }
        }
    }
}

#endregion


#region ============= MODELB

query readModelB($where: ModelBFilterInput! ) {
    readModelB(where: $where ) {
        id
    }
}

query listModelBs() {
    listModelBs() {
        total
        page
        pages
        hasNext
        hasPrev
        indexStartObj
        indexEndObj
        objects {
            id
        }
    }
}

query searchModelBs($where: ModelBFilterInput $orderBy: ModelBOrderByInput $paginated: PaginationConfigInput ) {
    searchModelBs(where: $where orderBy: $orderBy paginated: $paginated ) {
        total
        page
        pages
        hasNext
        hasPrev
        indexStartObj
        indexEndObj
        objects {
            id
        }
    }
}

mutation createModelBs($input: [CreateModelBInput!] ) {
    createModelBs(input: $input ) {
        objects {
            id
        }
        errors {
            objectPosition
            errors {
                field
                messages
            }
        }
    }
}

mutation updateModelBs($input: [UpdateModelBInput!] ) {
    updateModelBs(input: $input ) {
        objects {
            id
        }
        errors {
            objectPosition
            errors {
                field
                messages
            }
        }
    }
}

mutation deleteModelBs($where: ModelBFilterInput! ) {
    deleteModelBs(where: $where ) {
        success
        objects {
            id
        }
        errors {
            objectPosition
            errors {
                field
                messages
            }
        }
    }
}

mutation deactivateModelBs($where: ModelBFilterInput! ) {
    deactivateModelBs(where: $where ) {
        objects {
            id
        }
        errors {
            objectPosition
            errors {
                field
                messages
            }
        }
    }
}

mutation activateModelBs($where: ModelBFilterInput! ) {
    activateModelBs(where: $where ) {
        objects {
            id
        }
        errors {
            objectPosition
            errors {
                field
                messages
            }
        }
    }
}

#endregion


#region ============= MODELC

query readModelC($where: ModelCFilterInput! ) {
    readModelC(where: $where ) {
        id
    }
}

query listModelCs() {
    listModelCs() {
        total
        page
        pages
        hasNext
        hasPrev
        indexStartObj
        indexEndObj
        objects {
            id
        }
    }
}

query searchModelCs($where: ModelCFilterInput $orderBy: ModelCOrderByInput $paginated: PaginationConfigInput ) {
    searchModelCs(where: $where orderBy: $orderBy paginated: $paginated ) {
        total
        page
        pages
        hasNext
        hasPrev
        indexStartObj
        indexEndObj
        objects {
            id
        }
    }
}

mutation createModelCs($input: [CreateModelCInput!] ) {
    createModelCs(input: $input ) {
        objects {
            id
        }
        errors {
            objectPosition
            errors {
                field
                messages
            }
        }
    }
}

mutation updateModelCs($input: [UpdateModelCInput!] ) {
    updateModelCs(input: $input ) {
        objects {
            id
        }
        errors {
            objectPosition
            errors {
                field
                messages
            }
        }
    }
}

mutation deleteModelCs($where: ModelCFilterInput! ) {
    deleteModelCs(where: $where ) {
        success
        objects {
            id
        }
        errors {
            objectPosition
            errors {
                field
                messages
            }
        }
    }
}

mutation deactivateModelCs($where: ModelCFilterInput! ) {
    deactivateModelCs(where: $where ) {
        objects {
            id
        }
        errors {
            objectPosition
            errors {
                field
                messages
            }
        }
    }
}

mutation activateModelCs($where: ModelCFilterInput! ) {
    activateModelCs(where: $where ) {
        objects {
            id
        }
        errors {
            objectPosition
            errors {
                field
                messages
            }
        }
    }
}

#endregion


#region ============= MODELD

query readModelD($where: ModelDFilterInput! ) {
    readModelD(where: $where ) {
        id
    }
}

query listModelDs() {
    listModelDs() {
        total
        page
        pages
        hasNext
        hasPrev
        indexStartObj
        indexEndObj
        objects {
            id
        }
    }
}

query searchModelDs($where: ModelDFilterInput $orderBy: ModelDOrderByInput $paginated: PaginationConfigInput ) {
    searchModelDs(where: $where orderBy: $orderBy paginated: $paginated ) {
        total
        page
        pages
        hasNext
        hasPrev
        indexStartObj
        indexEndObj
        objects {
            id
        }
    }
}

mutation createModelDs($input: [CreateModelDInput!] ) {
    createModelDs(input: $input ) {
        objects {
            id
        }
        errors {
            objectPosition
            errors {
                field
                messages
            }
        }
    }
}

mutation updateModelDs($input: [UpdateModelDInput!] ) {
    updateModelDs(input: $input ) {
        objects {
            id
        }
        errors {
            objectPosition
            errors {
                field
                messages
            }
        }
    }
}

mutation deleteModelDs($where: ModelDFilterInput! ) {
    deleteModelDs(where: $where ) {
        success
        objects {
            id
        }
        errors {
            objectPosition
            errors {
                field
                messages
            }
        }
    }
}

mutation deactivateModelDs($where: ModelDFilterInput! ) {
    deactivateModelDs(where: $where ) {
        objects {
            id
        }
        errors {
            objectPosition
            errors {
                field
                messages
            }
        }
    }
}

mutation activateModelDs($where: ModelDFilterInput! ) {
    activateModelDs(where: $where ) {
        objects {
            id
        }
        errors {
            objectPosition
            errors {
                field
                messages
            }
        }
    }
}

#endregion


#region ============= MODELE

query readModelE($where: ModelEFilterInput! ) {
    readModelE(where: $where ) {
        id
    }
}

query listModelEs() {
    listModelEs() {
        total
        page
        pages
        hasNext
        hasPrev
        indexStartObj
        indexEndObj
        objects {
            id
        }
    }
}

query searchModelEs($where: ModelEFilterInput $orderBy: ModelEOrderByInput $paginated: PaginationConfigInput ) {
    searchModelEs(where: $where orderBy: $orderBy paginated: $paginated ) {
        total
        page
        pages
        hasNext
        hasPrev
        indexStartObj
        indexEndObj
        objects {
            id
        }
    }
}

mutation createModelEs($input: [CreateModelEInput!] ) {
    createModelEs(input: $input ) {
        objects {
            id
        }
        errors {
            objectPosition
            errors {
                field
                messages
            }
        }
    }
}

mutation updateModelEs($input: [UpdateModelEInput!] ) {
    updateModelEs(input: $input ) {
        objects {
            id
        }
        errors {
            objectPosition
            errors {
                field
                messages
            }
        }
    }
}

mutation deleteModelEs($where: ModelEFilterInput! ) {
    deleteModelEs(where: $where ) {
        success
        objects {
            id
        }
        errors {
            objectPosition
            errors {
                field
                messages
            }
        }
    }
}

mutation deactivateModelEs($where: ModelEFilterInput! ) {
    deactivateModelEs(where: $where ) {
        objects {
            id
        }
        errors {
            objectPosition
            errors {
                field
                messages
            }
        }
    }
}

mutation activateModelEs($where: ModelEFilterInput! ) {
    activateModelEs(where: $where ) {
        objects {
            id
        }
        errors {
            objectPosition
            errors {
                field
                messages
            }
        }
    }
}

#endregion


#endregion

#region ============= ADMIN

#region ============= LOGENTRY

#endregion


#endregion

#region ============= AUTH

#region ============= PERMISSION

#endregion


#region ============= GROUP

#endregion


#region ============= USER

#endregion


#endregion

#region ============= CONTENTTYPES

#region ============= CONTENTTYPE

#endregion


#endregion

#region ============= SESSIONS

#region ============= SESSION

#endregion


#endregion

#region ============= MESSAGES

#endregion

#region ============= STATICFILES

#endregion

#region ============= GRAPHENE_DJANGO

#endregion

