#region ============= RESTAURANT

#region ============= RESTAURANT

#endregion


#region ============= TABLE

#endregion


#endregion

#region ============= MENU

#region ============= MENU

query readMenu($where: MenuFilterInput! ) {
    readMenu(where: $where ) {
        id
    }
}

query listMenus() {
    listMenus() {
        total
        page
        pages
        hasNext
        hasPrev
        indexStartObj
        indexEndObj
        objects {
            id
        }
    }
}

query searchMenus($where: MenuFilterInput $orderBy: MenuOrderByInput $paginated: PaginatedInput ) {
    searchMenus(where: $where orderBy: $orderBy paginated: $paginated ) {
        total
        page
        pages
        hasNext
        hasPrev
        indexStartObj
        indexEndObj
        objects {
            id
        }
    }
}

mutation createMenus($input: [CreateMenuInput!] ) {
    createMenus(input: $input ) {
        objects {
            id
        }
        errors {
            objectPosition
            errors {
                field
                messages
            }
        }
    }
}

mutation updateMenus($input: [UpdateMenuInput!] ) {
    updateMenus(input: $input ) {
        objects {
            id
        }
        errors {
            objectPosition
            errors {
                field
                messages
            }
        }
    }
}

mutation deleteMenus($where: MenuFilterInput! ) {
    deleteMenus(where: $where ) {
        success
        objects {
            id
        }
        errors {
            objectPosition
            errors {
                field
                messages
            }
        }
    }
}

mutation deactivateMenus($where: MenuFilterInput! ) {
    deactivateMenus(where: $where ) {
        objects {
            id
        }
        errors {
            objectPosition
            errors {
                field
                messages
            }
        }
    }
}

mutation activateMenus($where: MenuFilterInput! ) {
    activateMenus(where: $where ) {
        objects {
            id
        }
        errors {
            objectPosition
            errors {
                field
                messages
            }
        }
    }
}

#endregion


#region ============= MENUITEM

#endregion


#endregion

#region ============= CORE

#region ============= EMPLOYEEPROFILE

#endregion


#region ============= SCHEDULE

#endregion


#region ============= TIMESLOT

#endregion


#endregion

#region ============= ADMIN

#region ============= LOGENTRY

#endregion


#endregion

#region ============= AUTH

#region ============= PERMISSION

#endregion


#region ============= GROUP

#endregion


#region ============= USER

#endregion


#endregion

#region ============= CONTENTTYPES

#region ============= CONTENTTYPE

#endregion


#endregion

#region ============= SESSIONS

#region ============= SESSION

#endregion


#endregion

#region ============= MESSAGES

#endregion

#region ============= STATICFILES

#endregion

#region ============= GRAPHENE_DJANGO

#endregion

#region ============= NESTED_ADMIN

#endregion

