# Generated by Django 4.2 on 2024-03-17 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the menu', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='The status for enabling or disabling')),
                ('restaurants', models.ManyToManyField(help_text='The restaurants that have this menu', related_name='menus', to='restaurant.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the menu item', max_length=100)),
                ('description', models.TextField(help_text='The description of the menu item')),
                ('price', models.DecimalField(decimal_places=2, help_text='The price of the menu item', max_digits=5)),
                ('is_active', models.BooleanField(default=True, help_text='The status for enabling or disabling')),
                ('menu', models.ForeignKey(help_text='The menu that this item is a part of', on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='menu.menu')),
            ],
        ),
    ]
